repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: (migrations|crm_backend/crm_backend/settings/)
        args: [--profile, black, --line-length=88]

-   repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: (migrations|crm_backend/crm_backend/settings/)
        args: [--line-length=88]
